name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**.md", "docs/**", "LICENSE", ".github/CODEOWNERS"]
  pull_request:
    paths-ignore: ["**.md", "docs/**", "LICENSE", ".github/CODEOWNERS"]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go:
    uses: flagstonehq/.github/.github/workflows/go-ci.yml@main
    with:
      needs-db: true
