name: CI
on:
  push:
    branches: [main, dev]
  pull_request:

permissions:
  contents: read

jobs:
  go:
    uses: flagstonehq/.github/.github/workflows/go-ci.yml@main
    with:
      needs-db: true
